version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - '7976:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
  web:
    build: ./web
    ports:
      - '7979:80'
    volumes:
      - ./www:/var/www/html
      - ./web/log:/var/log/apache2
    depends_on:
      - mysql
volumes:
  db: